=== microsoft/az-partner-center-cli/schema_listing_config.json
{
  "$schema"    : "https://json-schema.org/draft/2020-12/schema",
  "$id"        : "https://example.com/product.schema.json",
  "title"      : "Azure Partner Center Listing Configurations",
  "description": "A configuration for a product in the Azure Partner Center",
  "type"       : "object",
  "properties" : {
    "offer_setup"            : {
      "description": "Azure Partner Center Submission Offer Setup settings",
      "type"       : "object",
      "properties" : {
        "alias"    : {
          "type": "string"
        },
        "testDrive": {
          "type": "boolean"
        },
        "crm"      : {
          "type": "string"
        }
      },
      "required"   : [
        "alias"
      ]
    },
    "property_settings"      : {
      "description": "Azure Partner Center Submission Property Settings",
      "type"       : "object",
      "properties" : {
        "categories": {
          "type" : "array",
          "items": {
            "type": "object"
          }
        }
      }
    },
    "offer_listing"          : {
      "description": "Azure Partner Center Submission Offer Listing Settings",
      "type"       : "object",
      "properties" : {
        "name"               : {
          "type": "string"
        },
        "summary"            : {
          "type": "string"
        },
        "short_description"  : {
          "type": "string"
        },
        "description"        : {
          "type": "string"
        },
        "keywords"           : {
          "type"     : "array",
          "items"    : {
            "type": "string"
          },
          "maxLength": 3
        },
        "listing_contacts"   : {
          "type": "list"
        },
        "listing_uris"       : {
          "type": "list"
        },
        "listing_logos"      : {
          "type": "list"
        },
        "listing_screenshots": {
          "type": "list"
        },
        "listing_videos"     : {
          "type": "list"
        }
      },
      "required"   : [
        "name",
        "summary",
        "description",
        "keywords",
        "listing_contacts",
        "listing_uris",
        "listing_logos"
      ]
    },
    "preview_audience"       : {
      "description": "Azure Partner Center Submission Preview Audience Settings",
      "type"       : "object",
      "properties" : {
        "subscriptions": {
          "type"       : "array",
          "items"      : {
            "type": "string"
          },
          "minItems"   : 1,
          "maxItems"   : 10,
          "uniqueItems": true
        }
      },
      "required"   : [
        "subscriptions"
      ]
    },
    "technical_configuration": {
      "description": "Azure Partner Center Submission Technical Configuration Settings",
      "type"       : "object",
      "properties" : {
        "tenant_id"     : {
          "type": "string"
        },
        "application_id": {
          "type": "string"
        }
      }
    },
    "plan_overview"          : {
      "description": "Azure Partner Center Submission Plan Overview Settings",
      "type"       : "array",
      "items"      : {
        "type"      : "object",
        "properties": {
          "type" : "array",
          "items": {
            "type"      : "object",
            "properties": {
              "plan_listing"            : {
                "type"      : "object",
                "properties": {
                  "title"      : {
                    "type": "string"
                  },
                  "summary"    : {
                    "type": "string"
                  },
                  "description": {
                    "type": "string"
                  }
                }
              },
              "pricing_and_availability": {
                "type"      : "object",
                "properties": {
                  "visibility"                 : {
                    "type": "string",
                    "enum": [
                      "Private",
                      "Public"
                    ]
                  },
                  "azure_private_subscriptions": {
                    "type" : "array",
                    "items": {
                      "type"      : "object",
                      "properties": {
                        "ID"         : {
                          "type": "string"
                        },
                        "Description": {
                          "type": "string"
                        }
                      },
                      "required"  : [
                        "ID"
                      ]
                    }
                  }
                }
              },
              "technical_configuration" : {
                "type"      : "object",
                "properties": {
                  "version"               : {
                    "type": "string"
                  },
                  "allowedCustomerActions": {
                    "type"     : "array",
                    "items"    : {
                      "type": "string"
                    },
                    "maxLength": 1
                  },
                  "allowedDataActions"    : {
                    "type"     : "array",
                    "items"    : {
                      "type": "string"
                    },
                    "maxLength": 1
                  },
                  "tenant_id"             : {
                    "type": "string"
                  },
                  "authorizations"        : {
                    "type"     : "array",
                    "items"    : {
                      "type"      : "object",
                      "properties": {
                        "id"  : {
                          "type": "string"
                        },
                        "role": {
                          "type": "string",
                          "enum": [
                            "Owner",
                            "Contributor"
                          ]
                        }
                      }
                    },
                    "minLength": 1,
                    "maxLength": 10
                  },
                  "policy_settings"       : {
                    "type": "array"
                  }
                },
                "required"  : [
                  "version"
                ]
              }
            }
          }
        }
      },
      "properties" : {
        "type" : "array",
        "items": {
          "type"      : "object",
          "properties": {
            "plan_listing"            : {
              "type"      : "object",
              "properties": {
                "title"      : {
                  "type": "string"
                },
                "summary"    : {
                  "type": "string"
                },
                "description": {
                  "type": "string"
                }
              }
            },
            "pricing_and_availability": {
              "type"      : "object",
              "properties": {
                "visibility"                 : {
                  "type": "string",
                  "enum": [
                    "private",
                    "public"
                  ]
                },
                "azure_private_subscriptions": {
                  "type" : "array",
                  "items": {
                    "type"      : "object",
                    "properties": {
                      "ID"         : {
                        "type": "string"
                      },
                      "Description": {
                        "type": "string"
                      }
                    },
                    "required"  : [
                      "ID"
                    ]
                  }
                }
              }
            },
            "technical_configuration" : {
              "type"      : "object",
              "properties": {
                "version"               : {
                  "type": "string"
                },
                "allowedCustomerActions": {
                  "type"     : "array",
                  "items"    : {
                    "type": "string"
                  },
                  "maxLength": 1
                },
                "allowedDataActions"    : {
                  "type"     : "array",
                  "items"    : {
                    "type": "string"
                  },
                  "maxLength": 1
                },
                "tenant_id"             : {
                  "type": "string"
                },
                "authorizations"        : {
                  "type"     : "array",
                  "items"    : {
                    "type"      : "object",
                    "properties": {
                      "id"  : {
                        "type": "string"
                      },
                      "role": {
                        "type": "string",
                        "enum": [
                          "Owner",
                          "Contributor"
                        ]
                      }
                    }
                  },
                  "minLength": 1,
                  "maxLength": 10
                },
                "policy_settings"       : {
                  "type": "array"
                }
              },
              "required"  : [
                "version"
              ]
            }
          }
        }
      }
    },
    "co-sell"                : {
      "description": "Azure Partner Center Submission Co-sell Settings",
      "type"       : "object",
      "properties" : {}
    },
    "resell"                 : {
      "description": "Azure Partner Center Submission Resell Settings",
      "type"       : "object",
      "properties" : {}
    }
  },
  "required"   : [
    "offer_setup",
    "property_settings",
    "offer_listing",
    "preview_audience",
    "plan_overview"
  ]
}

=== microsoft/az-partner-center-cli/template.listing_config.json
{
  "$schema"                : "https://raw.githubusercontent.com/microsoft/AI/master/.ci/listing_config_schema.json",
  "offer_setup"            : {
    "alias"    : "industrail-ai-ama",
    "testDrive": false,
    "crm"      : ""
  },
  "property_settings"      : {
    "category"   : "analytics",
    "categories": [
      {
        "category"   : "analytics",
        "subcategory": [
          "Big Data",
          "Data Analytics"
        ]
      }
    ]
  },
  "offer_listing"          : {
    "title"              : "MMLSpark on Databricks",
    "publisher_name"     : "Microsoft Corporation",
    "name"               : "MMLSpark on Databricks",
    "summary"            : "<Search results Summary*>",
    "short_description"  : "<Short description*>",
    "description"        : "<Description>",
    "keywords"           : [
      "design",
      "simulation",
      "engineer"
    ],
    "listing_contacts"   : [
      {
        "type" : "CustomerSupport",
        "email": "name@email.com",
        "name" : "FirstName LastName",
        "phone": "+5555555555",
        "uri"  : "https://website.design/moreinfo/contactus"
      },
      {
        "type" : "Engineering",
        "email": "name@company.com",
        "name" : "Name Name",
        "phone": "+5555555555"
      }
    ],
    "listing_uris"       : [
      {
        "type"       : "PrivacyUri",
        "displayText": "Privacy Url",
        "uri"        : "https://website.design/eula"
      },
      {
        "type"       : "PublicCloudSupport",
        "displayText": "Privacy PublicCloudSupport",
        "uri"        : "https://website.design/PublicCloudSupport"
      }
    ],
    "listing_logos"      : {
      "logo_large" : "r_216_216.png",
      "logo_small" : "r_48_48.png",
      "logo_medium": "r_90_90.png",
      "logo_wide"  : "r_255_115.png"
    },
    "listing_screenshots": {},
    "listing_videos"     : {}
  },
  "preview_audience"       : {
    "subscriptions": [
      "422895b2-0fda-4709-9ab8-7df1295fedd7"
    ]
  },
  "technical_configuration": {
    "_note"         : "Only required for emitting metering events",
    "tenant_id"     : "<AAD Tenant Id>",
    "application_id": "<AAD Application ID>"
  },
  "plan_overview"          : [
    {
      "plan_listing"            : {
        "title"      : "website.Design",
        "summary"    : "Summary for Test",
        "description": "Description for Test"
      },
      "pricing_and_availability": {
        "visibility"                 : "private",
        "azure_private_subscriptions": [
          {
            "ID": "422895b2-0fda-4709-9ab8-7df1295fedd7"
          }
        ]
      },
      "technical_configuration" : {
        "version"               : "0.0.0",
        "allowedCustomerActions": [
          "Microsoft.Storage/*;Microsoft.MachineLearningServices/*;Microsoft.DocumentDB/*;Microsoft.Kubernetes/*;Microsoft.Insights/*;Microsoft.KeyVault/*;Microsoft.Databricks/*;Microsoft.ManagedIdentity/*;Microsoft.ContainerService/*;Microsoft.MachineLearning/*;Microsoft.Synapse/*;Microsoft.Network/*"
        ],
        "allowedDataActions"    : [
          "Microsoft.Storage/*;Microsoft.MachineLearningServices/*;Microsoft.DocumentDB/*;Microsoft.Kubernetes/*;Microsoft.Insights/*;Microsoft.KeyVault/*;Microsoft.Databricks/*;Microsoft.ManagedIdentity/*;Microsoft.ContainerService/*;Microsoft.MachineLearning/*;Microsoft.Synapse/*;Microsoft.Network/*"
        ],
        "tenant_id"             : "<AAD Tenant Id>",
        "authorizations"        : [
          {
            "id"  : "<AAD Owner Application ID>",
            "role": "Owner"
          },
          {
            "id"  : "<AAD Contributor Application ID>",
            "role": "Contributor"
          }
        ],
        "policy_settings"       : []
      }
    }
  ],
  "co-sell"                : {},
  "resell"                 : {}
}
